# ofono configuration for Galaxy Tab S7 LTE (gts7l)
[Settings]
SetRadioCapability=off
emptyPinQuery=false
radioPowerCycle=false
confirmRadioPowerOn=false

[ril_0]
transport=binder:name=slot1;interface=radio@1.6
name=slot1
