#!/bin/bash
# Dump the list of kernel modules the stock/LineageOS system loads, so systemd
# can load the same set under Ubuntu Touch.
#
# Run with the tablet booted into TWRP (adb available) or into stock Android
# with USB debugging on.
set -euo pipefail

OUT="overlay/system/etc/modules-load.d/gts7l.conf"

adb wait-for-device
{
    echo "# Generated by tools/gen-modules-load.sh on $(date -u +%F)"
    adb shell 'ls /vendor/lib/modules/*.ko 2>/dev/null || ls /lib/modules/*/*.ko' \
        | sed 's|.*/||; s|\.ko$||' | tr -d '\r' | sort -u
} > "$OUT"

echo "wrote $OUT ($(grep -cv '^#' "$OUT") modules)"
echo "Cross-check against a running stock system with: adb shell lsmod"
